services:
  - type: web
    name: symulator-produkcji-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: symulator-produkcji-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_API_URL
        value: https://symulator-produkcji-backend.onrender.com
